# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sloppy
description_footer: Powered by HPL
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
logo: /assets/favicon.png

permalink: /:year/:month/:day/:title/




# Build settings
markdown: kramdown
kramdown:
  input: GFM
  
highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# other links
twitter_username: 
facebook_username: 
github_username: hao-pl
email: hao-pl@outlook.com
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

# excerpt
excerpt_separator: "\n\n\n\n"

paginate: 12
plugins: 
  - jekyll-paginate
  - jemoji
